blank_issues_enabled: false
contact_links:
  - name: Food+ Discord
    url: https://discord.gg/404
    about: For general questions about mod features, please join the discord rather than opening a issue.
