blank_issues_enabled: false
contact_links:
  - name: Food+ Discord
    url: https://discord.gg/invalid-link-404 # Not a real link Discord Server WIP
    about: For general questions about mod features, please join the discord rather than opening a issue.
